<a href="https://colab.research.google.com/github/thorat1607/thorat1607/blob/ML_practical/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Tutorial

1. Import numpy library and its version:

In [ ]:
import numpy as np

print(np.__version__)


1.21.6


2. Numpy Creating Arrays:

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


3. Numpy Array Dimension:

In [ ]:
a = np.array(16)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3], [4,5,6], [7,8,9]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


4. Numpy Array Shape:

In [ ]:
#arr = np.array([1,2,3,4,5], ndmin=5)
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print("number of dimension:", arr.ndim )
print("Shape of an array:", arr.shape)


[[[[[1 2 3 4]]]]]
number of dimension: 5
Shape of an array: (1, 1, 1, 1, 4)


5. Numpy Array Index: 

In [ ]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr)
arr[0,1,2]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


6

6. Numpy Array Slicing:

In [ ]:
#printing odd numbers from array
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr[0:12:2])

[ 1  3  5  7  9 11]


7. Numpy Array Datatypes:

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array(["Parth", "Arjun", "Messi"])
print(a.dtype, "\n", b.dtype)


int64 
 <U5


8. Numpy Reshape Array:

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12]) #1-D array
b = a.reshape(4,3) #2-D array
c = a.reshape(2,3,2) #3-D array
print( b)
print("\n",c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


9. Numpy Array Iterating:

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b = a.reshape(4,3)
for x in b:
  print(x)
for i in np.nditer(b):
  print(i)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]
1
2
3
4
5
6
7
8
9
10
11
12


10. Numpy joining Array:

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
#d = np.concatenate((a,b),axis=1)
e = np.hstack((a,b))#stack along row
f = np.vstack((a,b))#stack along column
g = np.dstack((a,b))#stack along depth
print(c, "\n\n", e, "\n\n", f, "\n\n", g) 

[1 2 3 4 5 6] 

 [1 2 3 4 5 6] 

 [[1 2 3]
 [4 5 6]] 

 [[[1 4]
  [2 5]
  [3 6]]]


11. Numpy Array Split:

In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array_split(a, 3)
c = np.array_split(a, 3, axis=1)
print(b)
print(c)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


12. Numpy Array Search & Sort

In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.where(a == 7)#to search index no. of given value
c = np.where(a%2==0)#to search index value of even no. from array
print(b)
print(c)

arr = np.array([3,4,5,1,2,9,6,7,8])
x = np.sort(arr)#to sort given array 
print("\n\n",x)

(array([6]),)
(array([1, 3, 5, 7]),)


 [1 2 3 4 5 6 7 8 9]


13. Numpy Filter Array

In [ ]:
a = np.array([1,2,3,4,5,6,7])
filter_a = a>3
b = a[filter_a]
print(filter_a)
print(b)

[False False False  True  True  True  True]
[4 5 6 7]
