<a href="https://colab.research.google.com/github/thorat1607/thorat1607/blob/ML_practical/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Tutorial

In [ ]:
import numpy as np

print(np.__version__)


1.21.6


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
a = np.array(16)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3], [4,5,6], [7,8,9]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
#arr = np.array([1,2,3,4,5], ndmin=5)
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print("number of dimension:", arr.ndim )
print("Shape of an array:", arr.shape)


[[[[[1 2 3 4]]]]]
number of dimension: 5
Shape of an array: (1, 1, 1, 1, 4)


In [ ]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr)
arr[0,1,2]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


6

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr[0:12:2])

[ 1  3  5  7  9 11]
